import './styling/main.scss'
import { Inter } from 'next/font/google'
import { Open_Sans } from 'next/font/google'
import Header from './components/Header'
import Footer from './components/Footer'

const inter = Inter({ subsets: ['latin'] })
const open  = Open_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App 12',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={open.className} data-body="dc">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
